const products=[
   
        {Name:"Adam and Eve Apple Juice 200ml",
        srcImg:"../products/EveAppleJuice.PNG",
            UnitPrice:270.00,
            pricefor3:2.89,
            quantity:1, 
            Quantityinstock:6,
            instock:true,id:21},

            {Name:"Heineken 6pk 300ml",
        srcImg:"../products/heinekin6pk.PNG",
            UnitPrice:187.00,
            pricefor3:2.89,
            quantity:1, 
            Quantityinstock:24,
            instock:true,id:78},

            {Name:"N95 Mask 25pcs",
            srcImg:"../products/kn95mask.PNG",
                UnitPrice:600.00,
                pricefor3:2.89,
                quantity:1, 
                Quantityinstock:24,
                instock:true,id:456}, {Name:"Adam and Eve Apple Juice 200ml",
                srcImg:"../products/EveAppleJuice.PNG",
                    UnitPrice:270.00,
                    pricefor3:2.89,
                    quantity:1, 
                    Quantityinstock:32,
                    instock:true,id:232},

                    {Name:"Heineken 6pk 300ml",
                srcImg:"../products/heinekin6pk.PNG",
                    UnitPrice:187.00,
                    pricefor3:2.89,
                    quantity:1, 
                    Quantityinstock:24,
                    instock:true,id:154},

                    {Name:"N95 Mask 25pcs",
                    srcImg:"../products/kn95mask.PNG",
                        UnitPrice:600.00,
                        pricefor3:2.89,
                        quantity:1, 
                        Quantityinstock:24,
                        instock:true,id:753},
                        {Name:"Adam and Eve Apple Juice 200ml",
        srcImg:"../products/EveAppleJuice.PNG",
            UnitPrice:270.00,
            pricefor3:2.89,
            quantity:1, 
            Quantityinstock:32,
            instock:true, id:192},

            {Name:"Heineken 6pk 300ml",
        srcImg:"../products/heinekin6pk.PNG",
            UnitPrice:187.00,
            pricefor3:2.89,
            quantity:1, 
            Quantityinstock:24,
            instock:true,id:635},

            {Name:"N95 Mask 25pcs",
            srcImg:"../products/kn95mask.PNG",
                UnitPrice:600.00,
                pricefor3:2.89,
                quantity:1, 
                Quantityinstock:24,
                instock:true,id:394}, {Name:"Adam and Eve Apple Juice 200ml",
                srcImg:"../products/EveAppleJuice.PNG",
                    UnitPrice:270.00,
                    pricefor3:2.89,
                    quantity:1, 
                    Quantityinstock:32,
                    instock:true,id:66},

                    {Name:"Heineken 6pk 300ml",
                srcImg:"../products/heinekin6pk.PNG",
                    UnitPrice:187.00,
                    pricefor3:2.89,
                    quantity:1, 
                    Quantityinstock:24,
                    instock:false,id:152},

                    {Name:"N95 Mask 25pcs",
                    srcImg:"../products/kn95mask.PNG",
                        UnitPrice:600.00,
                        pricefor3:2.89,
                        quantity:1, 
                        Quantityinstock:24,
                        instock:true,id:636}

        ]


